minio:
  root_user: winebot
  root_password: TestPassword123
  extra_args: []
  additional_envs: []

network:
  api_port: 9000
  console_port: 9001
  certificate_id: null
  domain: ""

storage:
  export:
    type: host_path
    host_path: /mnt/Storage/models/minio
  additional_storage: []

resources:
  limits:
    cpu: 2
    memory: 2048
